from typing import Protocol
from phoenix6.hardware import TalonFX, CANcoder

class PIDMotor(TalonFX, CANcoder):
    def configPIDF(self, slot: int, p: float, i: float, d: float, f: float): ...
    def with_slot0(self, p: float, i: float, d: float, f: float): ...
    def configPID(self, slot: int, p: float, i: float, d: float): ...
    def with_pid0(self, p: float, i: float, d: float): ...